### PR TITLE
Support Olfaction and other Misc Changes

### PR DESCRIPTION
**Pull request by Alium58**
Made a few minor changes, not done with what I would like to change yet. Putting this up now as a draft to get @RESPRiT  your input on this - are you open to others submitting PRs? Or would you prefer I fork it? 

Thanks for making this great script. Used it for the first time today and worked well overall. If you are amenable to PR's from others, I'll write out more detail on what I've actually changed. lmk

### CODE REVIEW

**Comment by RESPRiT** [comment]
Thanks for contributing! Unfortunately, I haven't maintained any ASH scripts for a long time, so I would recommend just forking and starting your own branch. If you want, I can update the forum post to include a link to your repo :)

**Comment by Alium58** [comment]
Sounds good - thanks for the quick reply! I'll let you know exactly how we decide to fork it.

**Comment by Alium58** [comment]
We have decided to fork it to: https://github.com/loathers/bountiful

Updating the forum post would be most excellent - thank you! :)

**Comment by RESPRiT** [comment]
Updated - cheers!

**Pull request closed without merging**
